export type AttractionType =
  | "tobogan"
  | "piscina"
  | "rio"
  | "atraccion-familiar"
  | "zona-niños"
  | "show"
  | "servicio";

export type CongestionLevel = "low" | "medium" | "high";

export interface Attraction {
  id: string;
  name: string;
  type: AttractionType;
  capacity: number;
  baseOccupancy: number;
  baseWaitMin: number;
  position: { x: number; y: number };
  zone: "norte" | "centro" | "sur" | "este" | "oeste";
  hasReservation: boolean;
  hasCoolingZone: boolean;
  description: string;
  criticalInAudit: boolean;
}

export const ATTRACTIONS: Attraction[] = [
  {
    id: "pisciflash",
    name: "Pisciflash",
    type: "tobogan",
    capacity: 120,
    baseOccupancy: 190,
    baseWaitMin: 75,
    position: { x: 245, y: 145 },
    zone: "centro",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Tobogán de alta velocidad, doble fila identificada",
    criticalInAudit: true,
  },
  {
    id: "piscitornado",
    name: "Piscitornado",
    type: "tobogan",
    capacity: 80,
    baseOccupancy: 120,
    baseWaitMin: 60,
    position: { x: 175, y: 105 },
    zone: "norte",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Tobogán tornado, fila sin sombrío",
    criticalInAudit: true,
  },
  {
    id: "anaconda",
    name: "Anaconda",
    type: "tobogan",
    capacity: 60,
    baseOccupancy: 70,
    baseWaitMin: 45,
    position: { x: 380, y: 165 },
    zone: "este",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Tobogán de flotadores, atascos frecuentes",
    criticalInAudit: true,
  },
  {
    id: "onda-extrema",
    name: "Onda Extrema",
    type: "tobogan",
    capacity: 60,
    baseOccupancy: 65,
    baseWaitMin: 40,
    position: { x: 425, y: 215 },
    zone: "este",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Tobogán extremo, reposición lenta de flotadores",
    criticalInAudit: true,
  },
  {
    id: "megatobogan",
    name: "Megatobogán",
    type: "tobogan",
    capacity: 100,
    baseOccupancy: 75,
    baseWaitMin: 28,
    position: { x: 95, y: 195 },
    zone: "oeste",
    hasReservation: true,
    hasCoolingZone: true,
    description: "Tobogán emblema con reserva digital activa",
    criticalInAudit: false,
  },
  {
    id: "pisciquantum",
    name: "Pisciquantum",
    type: "atraccion-familiar",
    capacity: 80,
    baseOccupancy: 32,
    baseWaitMin: 8,
    position: { x: 195, y: 285 },
    zone: "sur",
    hasReservation: false,
    hasCoolingZone: true,
    description: "Atracción familiar con baja afluencia",
    criticalInAudit: false,
  },
  {
    id: "rio-lento",
    name: "Río Lento del Sol",
    type: "rio",
    capacity: 200,
    baseOccupancy: 90,
    baseWaitMin: 4,
    position: { x: 305, y: 260 },
    zone: "sur",
    hasReservation: false,
    hasCoolingZone: true,
    description: "Río de relajación, alta capacidad disponible",
    criticalInAudit: false,
  },
  {
    id: "piscina-olas",
    name: "Piscina de Olas",
    type: "piscina",
    capacity: 350,
    baseOccupancy: 180,
    baseWaitMin: 0,
    position: { x: 285, y: 195 },
    zone: "centro",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Piscina principal de olas artificiales",
    criticalInAudit: false,
  },
  {
    id: "piscina-familiar",
    name: "Piscina Familiar",
    type: "piscina",
    capacity: 280,
    baseOccupancy: 95,
    baseWaitMin: 0,
    position: { x: 415, y: 285 },
    zone: "sur",
    hasReservation: false,
    hasCoolingZone: true,
    description: "Piscina para familias con niños pequeños",
    criticalInAudit: false,
  },
  {
    id: "kamikaze",
    name: "Kamikaze",
    type: "tobogan",
    capacity: 50,
    baseOccupancy: 38,
    baseWaitMin: 22,
    position: { x: 155, y: 65 },
    zone: "norte",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Tobogán de descenso libre",
    criticalInAudit: false,
  },
  {
    id: "rapidos",
    name: "Rápidos",
    type: "rio",
    capacity: 120,
    baseOccupancy: 65,
    baseWaitMin: 12,
    position: { x: 355, y: 95 },
    zone: "este",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Recorrido por rápidos con flotador",
    criticalInAudit: false,
  },
  {
    id: "splash-kids",
    name: "Splash Kids",
    type: "zona-niños",
    capacity: 150,
    baseOccupancy: 60,
    baseWaitMin: 0,
    position: { x: 105, y: 295 },
    zone: "oeste",
    hasReservation: false,
    hasCoolingZone: true,
    description: "Zona de juegos acuáticos infantiles",
    criticalInAudit: false,
  },
  {
    id: "torre-aventura",
    name: "Torre Aventura",
    type: "tobogan",
    capacity: 90,
    baseOccupancy: 58,
    baseWaitMin: 30,
    position: { x: 215, y: 215 },
    zone: "centro",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Complejo de toboganes con torre central",
    criticalInAudit: false,
  },
  {
    id: "burbujas",
    name: "Burbujas Mágicas",
    type: "zona-niños",
    capacity: 80,
    baseOccupancy: 25,
    baseWaitMin: 0,
    position: { x: 55, y: 250 },
    zone: "oeste",
    hasReservation: false,
    hasCoolingZone: true,
    description: "Atracción para niños con espuma y burbujas",
    criticalInAudit: false,
  },
  {
    id: "laguna-tropical",
    name: "Laguna Tropical",
    type: "piscina",
    capacity: 200,
    baseOccupancy: 80,
    baseWaitMin: 0,
    position: { x: 465, y: 145 },
    zone: "este",
    hasReservation: false,
    hasCoolingZone: true,
    description: "Piscina con ambientación tropical",
    criticalInAudit: false,
  },
  {
    id: "spa-natural",
    name: "Spa Natural",
    type: "atraccion-familiar",
    capacity: 40,
    baseOccupancy: 12,
    baseWaitMin: 0,
    position: { x: 495, y: 245 },
    zone: "este",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Zona de relajación con jacuzzis",
    criticalInAudit: false,
  },
  {
    id: "show-acuatico",
    name: "Show Acuático",
    type: "show",
    capacity: 400,
    baseOccupancy: 120,
    baseWaitMin: 0,
    position: { x: 255, y: 65 },
    zone: "norte",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Show en piscina principal, 3 funciones diarias",
    criticalInAudit: false,
  },
  {
    id: "punto-conservacion",
    name: "Área de Conservación",
    type: "atraccion-familiar",
    capacity: 60,
    baseOccupancy: 18,
    baseWaitMin: 0,
    position: { x: 525, y: 195 },
    zone: "este",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Recorrido educativo de fauna regional",
    criticalInAudit: false,
  },
  {
    id: "zona-comida-central",
    name: "Plaza de Comidas",
    type: "servicio",
    capacity: 250,
    baseOccupancy: 110,
    baseWaitMin: 8,
    position: { x: 305, y: 165 },
    zone: "centro",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Zona principal de alimentos",
    criticalInAudit: false,
  },
  {
    id: "tienda-recuerdos",
    name: "Tienda Recuerdos",
    type: "servicio",
    capacity: 60,
    baseOccupancy: 22,
    baseWaitMin: 0,
    position: { x: 145, y: 175 },
    zone: "oeste",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Tienda oficial Piscilago",
    criticalInAudit: false,
  },
  {
    id: "entrada-principal",
    name: "Entrada Principal",
    type: "servicio",
    capacity: 500,
    baseOccupancy: 80,
    baseWaitMin: 6,
    position: { x: 290, y: 335 },
    zone: "sur",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Acceso principal con pulseras NFC",
    criticalInAudit: false,
  },
  {
    id: "punto-pulsera",
    name: "Punto Recarga Pulsera",
    type: "servicio",
    capacity: 30,
    baseOccupancy: 8,
    baseWaitMin: 2,
    position: { x: 355, y: 295 },
    zone: "sur",
    hasReservation: false,
    hasCoolingZone: false,
    description: "Recarga de saldo en pulsera NFC",
    criticalInAudit: false,
  },
];

export function getCongestion(occupancyPct: number, waitMin: number): CongestionLevel {
  if (waitMin >= 45 || occupancyPct >= 85) return "high";
  if (waitMin >= 15 || occupancyPct >= 60) return "medium";
  return "low";
}

export function attractionById(id: string): Attraction | undefined {
  return ATTRACTIONS.find((a) => a.id === id);
}
